// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtBD3OHax2Q7laE8I7wBC1o1ZuHFx_VrI',
    appId: '1:680944072832:web:8be9a9f1666af9d0580e65',
    messagingSenderId: '680944072832',
    projectId: 'plastic-guard-c9b94',
    authDomain: 'plastic-guard-c9b94.firebaseapp.com',
    storageBucket: 'plastic-guard-c9b94.appspot.com',
    measurementId: 'G-33X3F791VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK9nMDrOKKZAafS16nZl75RETzetl4e7Y',
    appId: '1:680944072832:android:63c5a3177af331d6580e65',
    messagingSenderId: '680944072832',
    projectId: 'plastic-guard-c9b94',
    storageBucket: 'plastic-guard-c9b94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-BweXlIxLdftuoOzDd8ErWviMCQZNMkg',
    appId: '1:680944072832:ios:a8ec6d695b24d191580e65',
    messagingSenderId: '680944072832',
    projectId: 'plastic-guard-c9b94',
    storageBucket: 'plastic-guard-c9b94.appspot.com',
    iosBundleId: 'com.example.planetGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-BweXlIxLdftuoOzDd8ErWviMCQZNMkg',
    appId: '1:680944072832:ios:f487e0bcdb0b7506580e65',
    messagingSenderId: '680944072832',
    projectId: 'plastic-guard-c9b94',
    storageBucket: 'plastic-guard-c9b94.appspot.com',
    iosBundleId: 'com.example.planetGuard.RunnerTests',
  );
}
